# Generated by Django 2.2.6 on 2019-11-09 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_produit_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=10),
        ),
    ]
