# Generated by Django 2.2.6 on 2019-11-09 10:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20191109_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='famille',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), null=True, size=10),
        ),
    ]
