# Generated by Django 2.2.6 on 2019-11-09 10:44

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20191109_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(null=True),
        ),
    ]
