# Generated by Django 2.2.6 on 2019-11-09 10:47

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='periode_promo',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=None),
            preserve_default=False,
        ),
    ]
