# Generated by Django 2.2.6 on 2019-11-09 10:49

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_produit_periode_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(null=True, verbose_name=range(1, 50)),
        ),
    ]
