# Generated by Django 2.2.6 on 2019-11-09 11:31

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20191109_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_cat', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_produit', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_sous', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
